[tool.mypy]
exclude = [
    'venv',
    '.*tmp.*',
    '.*untitled.*',
]

ignore_missing_imports = true
follow_imports = 'silent'
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_reexport = true
no_implicit_optional = false
# disallow_untyped_defs = true  # for strict mypy

[[tool.mypy.overrides]]
module = 'tests.*'
disable_error_code = ['union-attr']


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[tool.black]
line-length = 119                   # max line length
skip-string-normalization = 1       # disable converting single quote to double
# by default black exclude all .gitignore files. here is regex pattern to extend this list
# extend-exclude = 'alembic/|migrations/'

[tool.isort]
skip_glob = '*tmp*'
profile = 'black'
